--------------------------------------------------------------------------------
-- softmax.vhd -- integer softmax over one attention row
--
-- Consumes one row of SEQ_LEN int8 scores and produces SEQ_LEN int8
-- probabilities summing to approximately Q_SCALE. The attention stage feeds it
-- SEQ_LEN rows per image.
--
-- Numerically stable by construction
-- ---------------------------------
-- Every exponent argument is (score - row_max), which is at most zero, so the
-- exponential never overflows and the table only has to cover negative inputs.
-- That is the whole reason for the max subtraction.
--
-- The exponential is one table lookup
-- -----------------------------------
-- The reference implementation clamps the magnitude of the difference at
-- Q_SCALE, scales it into a 256-entry Q16 table, reverses the index and shifts
-- the result from Q16 down to Q1.7. None of that depends on anything but the
-- magnitude, and only 26 of the 256 entries are reachable -- so the entire path
-- collapses into EXP_BY_MAG, a 129-byte table in vit_pkg generated by
-- evaluating the Python reference across its whole input domain. What would
-- have been a multiply, a divide, an index reversal and a shift is a single
-- ROM read, and it is bit-identical by construction.
--
-- Schedule
-- --------
--   S_MAX    1 cycle    row maximum, from a comparison tree
--   S_EXP    SEQ_LEN    one exponential per cycle, accumulating the denominator
--   S_DIV    SEQ_LEN    one normalising division per cycle
--
-- About 34 cycles per row and about 550 per image, against roughly 12,000 for
-- the matrix multiplies, so softmax is under 5% of the frame and there is no
-- reason to spend area making it wider.
--
-- The divide
-- ----------
-- This is the one true division in the datapath. It is exact integer floor
-- division, matching the reference; a reciprocal-multiply approximation would
-- be cheaper but is off by one on some inputs, which would break bit-exactness.
-- One divider is instantiated and reused across the SEQ_LEN outputs. If
-- synthesis cannot close timing on it, the fix is a reciprocal estimate plus a
-- correction step ((q+1)*denom <= numerator), which is still exact -- not a
-- looser comparison in the testbench.
--
-- The denominator cannot be zero: the row maximum always contributes
-- EXP_BY_MAG(0) = 127. The reference's uniform-distribution guard for a
-- non-positive denominator is therefore unreachable, and is reproduced here
-- only so the two implementations stay literally interchangeable.
--------------------------------------------------------------------------------

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

    use work.vit_pkg.all;

entity softmax is
    port (
        clk  : in std_logic;
        rstn : in std_logic;                    -- synchronous, active low

        -- One complete row in, one complete row out. i_valid is accepted only
        -- while o_busy is low.
        i_row   : in  q8_row_t;
        i_valid : in  std_logic;

        o_row   : out q8_row_t;
        o_valid : out std_logic;                -- 1-cycle strobe
        o_busy  : out std_logic
    );
end entity softmax;

architecture rtl of softmax is

    type state_t is (S_IDLE, S_EXP, S_DIV, S_EMIT);
    signal state : state_t := S_IDLE;

    signal row_r : q8_row_t := (others => (others => '0'));

    -- Exponentials are at most 127 and there are SEQ_LEN of them, so the
    -- denominator needs clog2(PE_ROWS * 127) bits; 16 is comfortable.
    type exp_arr_t is array (0 to PE_ROWS - 1) of unsigned(7 downto 0);
    signal exps  : exp_arr_t := (others => (others => '0'));
    signal denom : unsigned(15 downto 0) := (others => '0');

    signal idx    : integer range 0 to PE_ROWS - 1 := 0;
    signal result : q8_row_t := (others => (others => '0'));

    -- Combinational maximum over the incoming row.
    function row_max (r : q8_row_t) return signed is
        variable m : signed(7 downto 0) := r(0);
    begin
        for i in 1 to PE_ROWS - 1 loop
            if r(i) > m then
                m := r(i);
            end if;
        end loop;
        return m;
    end function row_max;

    signal max_r : signed(7 downto 0) := (others => '0');

begin

    o_busy <= '0' when state = S_IDLE else '1';
    o_row  <= result;

    p_softmax : process(clk) is
        variable diff : integer;
        variable mag  : integer;
        variable num  : unsigned(15 downto 0);
        variable q    : unsigned(15 downto 0);
    begin
        if rising_edge(clk) then
            o_valid <= '0';

            if rstn = '0' then
                state <= S_IDLE;
                idx   <= 0;
                denom <= (others => '0');

            else
                case state is

                    when S_IDLE =>
                        if i_valid = '1' then
                            row_r <= i_row;
                            max_r <= row_max(i_row);
                            denom <= (others => '0');
                            idx   <= 0;
                            state <= S_EXP;
                        end if;

                    -- One exponential per cycle, accumulating the denominator
                    -- as we go so no separate summation pass is needed.
                    when S_EXP =>
                        diff := to_integer(row_r(idx)) - to_integer(max_r);
                        mag  := -diff;                  -- diff <= 0 by construction
                        if mag > Q_SCALE then
                            mag := Q_SCALE;             -- table domain clamp
                        end if;

                        exps(idx) <= to_unsigned(EXP_BY_MAG(mag), 8);
                        denom     <= denom + to_unsigned(EXP_BY_MAG(mag), 8);

                        if idx = PE_ROWS - 1 then
                            idx   <= 0;
                            state <= S_DIV;
                        else
                            idx <= idx + 1;
                        end if;

                    -- Normalise: floor((e * Q_SCALE) / denom), clamped.
                    when S_DIV =>
                        if denom = 0 then
                            -- Unreachable (the row max contributes 127), kept
                            -- so this matches the reference exactly.
                            result(idx) <= to_signed(Q_SCALE / PE_ROWS, 8);
                        else
                            num := resize(exps(idx) * to_unsigned(Q_SCALE, 8), 16);
                            q   := num / denom;
                            if q > to_unsigned(INT8_MAX, 16) then
                                result(idx) <= to_signed(INT8_MAX, 8);
                            else
                                result(idx) <= signed(resize(q, 8));
                            end if;
                        end if;

                        if idx = PE_ROWS - 1 then
                            idx   <= 0;
                            state <= S_EMIT;
                        else
                            idx <= idx + 1;
                        end if;

                    -- One cycle so the final result(idx) write has landed
                    -- before o_valid advertises the row.
                    when S_EMIT =>
                        o_valid <= '1';
                        state   <= S_IDLE;

                end case;
            end if;
        end if;
    end process p_softmax;

end architecture rtl;
