--------------------------------------------------------------------------------
-- stage_map.vhd -- generated by cifar10_vit/sw/export_weights.py; DO NOT EDIT.
--
-- Where each matrix multiply's weights start in the ROM, and how big it is.
-- Generated alongside the ROM image itself so the controller and the data
-- cannot disagree about the layout.
--------------------------------------------------------------------------------

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

package stage_map is

    constant ROM_WORDS   : natural := 11456;
    constant BIAS_ENTRIES: natural := 524;

    -- patch_embed: 64 outputs, K = 192, 16 tiles
    constant PATCH_EMBED_ROM_BASE  : natural := 0;
    constant PATCH_EMBED_BIAS_BASE : natural := 0;
    constant PATCH_EMBED_K         : natural := 192;
    constant PATCH_EMBED_TILES     : natural := 16;
    constant PATCH_EMBED_SHIFT     : natural := 7;

    -- qkv: 192 outputs, K = 64, 48 tiles
    constant QKV_ROM_BASE  : natural := 3072;
    constant QKV_BIAS_BASE : natural := 64;
    constant QKV_K         : natural := 64;
    constant QKV_TILES     : natural := 48;
    constant QKV_SHIFT     : natural := 7;

    -- out_proj: 64 outputs, K = 64, 16 tiles
    constant OUT_PROJ_ROM_BASE  : natural := 6144;
    constant OUT_PROJ_BIAS_BASE : natural := 256;
    constant OUT_PROJ_K         : natural := 64;
    constant OUT_PROJ_TILES     : natural := 16;
    constant OUT_PROJ_SHIFT     : natural := 7;

    -- fc1: 128 outputs, K = 64, 32 tiles
    constant FC1_ROM_BASE  : natural := 7168;
    constant FC1_BIAS_BASE : natural := 320;
    constant FC1_K         : natural := 64;
    constant FC1_TILES     : natural := 32;
    constant FC1_SHIFT     : natural := 7;

    -- fc2: 64 outputs, K = 128, 16 tiles
    constant FC2_ROM_BASE  : natural := 9216;
    constant FC2_BIAS_BASE : natural := 448;
    constant FC2_K         : natural := 128;
    constant FC2_TILES     : natural := 16;
    constant FC2_SHIFT     : natural := 7;

    -- classifier: 12 outputs, K = 64, 3 tiles
    constant CLASSIFIER_ROM_BASE  : natural := 11264;
    constant CLASSIFIER_BIAS_BASE : natural := 512;
    constant CLASSIFIER_K         : natural := 64;
    constant CLASSIFIER_TILES     : natural := 3;
    constant CLASSIFIER_SHIFT     : natural := 7;

end package stage_map;
