--------------------------------------------------------------------------------
-- vit_pkg.vhd -- generated by cifar10_vit/sw/model_config.py; DO NOT EDIT.
--
-- Regenerate with:  python3 cifar10_vit/sw/model_config.py --export
--
-- Every dimension and fixed-point constant the RTL uses comes from here, and
-- from the same Python object the golden model and the QAT training code use,
-- so the three implementations cannot drift apart.
--------------------------------------------------------------------------------

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

package vit_pkg is

    -- ── Input ───────────────────────────────────────────────────
    constant IMG_H             : natural := 32;
    constant IMG_W             : natural := 32;
    constant IMG_C             : natural := 3;
    constant IMG_PIXELS        : natural := 3072;   -- bytes per image

    -- ── Tokenisation ────────────────────────────────────────────
    constant PATCH             : natural := 8;
    constant GRID              : natural := 4;      -- patches per side
    constant SEQ_LEN           : natural := 16;     -- tokens
    constant PATCH_DIM         : natural := 192;    -- values per patch

    -- ── Transformer ─────────────────────────────────────────────
    constant D_MODEL           : natural := 64;
    constant D_FF              : natural := 128;
    constant N_HEADS           : natural := 1;
    constant N_LAYERS          : natural := 1;
    constant N_CLASSES         : natural := 10;

    -- ── Fixed point ─────────────────────────────────────────────
    constant Q_BITS            : natural := 7;      -- Q1.7
    constant Q_SCALE           : natural := 128;    -- integer representing 1.0
    constant ACC_BITS          : natural := 32;     -- PE accumulator width
    constant LN_HEADROOM       : natural := 2;      -- extra >> on LayerNorm out
    constant ATTN_SHIFT        : natural := 10;     -- Q.K^T requant, folds 1/sqrt(d)
    constant GAP_SHIFT         : natural := 4;      -- average pool over SEQ_LEN
    constant INT8_MIN         : integer := -128;
    constant INT8_MAX         : integer := 127;

    -- ── PE array ────────────────────────────────────────────────
    constant PE_ROWS           : natural := 16;     -- maps to tokens (M)
    constant PE_COLS           : natural := 4;      -- maps to an N tile
    constant N_PE              : natural := 64;     -- MACs per cycle

    -- ── Derived sizes (for reference / sizing memories) ─────────
    constant TOTAL_PARAM_BYTES : natural := 46986;
    constant TOTAL_GEMM_CYCLES : natural := 11968;  -- PE-array cycles per image

    -- ── Elementwise operation selectors (elem_op.vhd) ───────────
    constant ELEM_POS  : std_logic_vector(1 downto 0) := "00";
    constant ELEM_ADD  : std_logic_vector(1 downto 0) := "01";
    constant ELEM_GELU : std_logic_vector(1 downto 0) := "10";
    constant ELEM_GAP  : std_logic_vector(1 downto 0) := "11";

    -- ── Types ───────────────────────────────────────────────────
    subtype q8_t   is signed(7 downto 0);
    subtype acc_t  is signed(31 downto 0);

    -- One PE-array column slice: PE_ROWS activations read in parallel.
    type q8_row_t  is array (0 to PE_ROWS - 1) of q8_t;
    -- One weight slice: PE_COLS weights for the current k.
    type q8_col_t  is array (0 to PE_COLS - 1) of q8_t;
    -- Accumulator readout: one column's worth of results.
    type acc_col_t is array (0 to PE_COLS - 1) of acc_t;

    -- exp(score - row_max) in Q1.7, indexed by the clamped magnitude
    -- of the difference. Generated from quant_ops._exp_q7_from_diff
    -- over its whole input domain; see model_config._render_exp_table.
    type exp_table_t is array (0 to 128) of integer range 0 to 127;
    constant EXP_BY_MAG : exp_table_t := (
        127, 127, 127, 127, 127, 127, 123, 123, 123, 123, 123, 118, 118, 118, 118, 118,
        113, 113, 113, 113, 113, 109, 109, 109, 109, 109, 105, 105, 105, 105, 105, 101,
        101, 101, 101, 101, 97, 97, 97, 97, 97, 93, 93, 93, 93, 93, 89, 89,
        89, 89, 89, 86, 86, 86, 86, 86, 83, 83, 83, 83, 83, 79, 79, 79,
        79, 79, 76, 76, 76, 76, 76, 73, 73, 73, 73, 73, 71, 71, 71, 71,
        71, 68, 68, 68, 68, 68, 65, 65, 65, 65, 65, 63, 63, 63, 63, 63,
        60, 60, 60, 60, 60, 58, 58, 58, 58, 58, 56, 56, 56, 56, 56, 54,
        54, 54, 54, 54, 51, 51, 51, 51, 51, 49, 49, 49, 49, 49, 48, 48,
        48
    );

    -- GELU, indexed by the raw int8 activation bit pattern (0..255,
    -- two's complement). Generated from quant_ops.build_gelu_lut.
    type gelu_table_t is array (0 to 255) of integer range -128 to 127;
    constant GELU_LUT : gelu_table_t := (
        0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6, 7, 7, 8,
        8, 9, 10, 10, 11, 11, 12, 13, 13, 14, 15, 15, 16, 17, 17, 18,
        19, 19, 20, 21, 21, 22, 23, 24, 24, 25, 26, 27, 27, 28, 29, 30,
        31, 31, 32, 33, 34, 35, 35, 36, 37, 38, 39, 39, 40, 41, 42, 43,
        44, 45, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 54, 55, 56, 57,
        58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73,
        74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89,
        90, 91, 92, 93, 94, 95, 96, 98, 99, 100, 101, 102, 103, 104, 105, 106,
        -20, -20, -20, -20, -20, -20, -20, -20, -20, -20, -21, -21, -21, -21, -21, -21,
        -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21,
        -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21, -21,
        -21, -21, -21, -21, -21, -20, -20, -20, -20, -20, -20, -20, -20, -20, -20, -19,
        -19, -19, -19, -19, -19, -19, -18, -18, -18, -18, -18, -17, -17, -17, -17, -17,
        -16, -16, -16, -16, -16, -15, -15, -15, -15, -14, -14, -14, -14, -13, -13, -13,
        -12, -12, -12, -11, -11, -11, -10, -10, -10, -9, -9, -9, -8, -8, -7, -7,
        -7, -6, -6, -5, -5, -5, -4, -4, -3, -3, -2, -2, -1, -1, 0, 0
    );
    -- Saturating requantiser: arithmetic shift right, then clamp to int8.
    -- Shared by every stage that closes out a matrix multiply.
    function requantize (acc : signed; shift : natural) return signed;

    -- Saturating int8 add, used by the residual connections.
    function add_sat8 (a : signed(7 downto 0); b : signed(7 downto 0))
        return signed;

    -- Index of the most significant set bit (leading-one detector), 0 for 0.
    function leading_one (v : unsigned) return natural;

    -- Bits needed to index n distinct values, minimum 1.
    function clog2 (n : positive) return natural;

end package vit_pkg;

package body vit_pkg is

    function requantize (acc : signed; shift : natural) return signed is
        variable shifted : signed(acc'length - 1 downto 0);
    begin
        -- shift_right on a signed value is arithmetic and rounds toward
        -- negative infinity, matching Python's and numpy's >> operators.
        shifted := shift_right(acc, shift);
        if shifted > to_signed(INT8_MAX, acc'length) then
            return to_signed(INT8_MAX, 8);
        elsif shifted < to_signed(INT8_MIN, acc'length) then
            return to_signed(INT8_MIN, 8);
        else
            return resize(shifted, 8);
        end if;
    end function requantize;

    function add_sat8 (a : signed(7 downto 0); b : signed(7 downto 0))
        return signed is
        variable sum : signed(8 downto 0);
    begin
        sum := resize(a, 9) + resize(b, 9);
        if sum > to_signed(INT8_MAX, 9) then
            return to_signed(INT8_MAX, 8);
        elsif sum < to_signed(INT8_MIN, 9) then
            return to_signed(INT8_MIN, 8);
        else
            return resize(sum, 8);
        end if;
    end function add_sat8;

    function leading_one (v : unsigned) return natural is
    begin
        -- Priority encoder: scan from the top, return the first set bit.
        for i in v'length - 1 downto 0 loop
            if v(i) = '1' then
                return i;
            end if;
        end loop;
        return 0;
    end function leading_one;

    function clog2 (n : positive) return natural is
        variable bits : natural := 0;
        variable v    : positive := 1;
    begin
        while v < n loop
            v    := v * 2;
            bits := bits + 1;
        end loop;
        if bits = 0 then
            return 1;                       -- always give at least one bit
        end if;
        return bits;
    end function clog2;

end package body vit_pkg;
