--------------------------------------------------------------------------------
-- vit_pkg.vhd -- generated by cifar10_vit/sw/model_config.py; DO NOT EDIT.
--
-- Regenerate with:  python3 cifar10_vit/sw/model_config.py --export
--
-- Every dimension and fixed-point constant the RTL uses comes from here, and
-- from the same Python object the golden model and the QAT training code use,
-- so the three implementations cannot drift apart.
--------------------------------------------------------------------------------

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

package vit_pkg is

    -- ── Input ───────────────────────────────────────────────────
    constant IMG_H             : natural := 32;
    constant IMG_W             : natural := 32;
    constant IMG_C             : natural := 3;
    constant IMG_PIXELS        : natural := 3072;   -- bytes per image

    -- ── Tokenisation ────────────────────────────────────────────
    constant PATCH             : natural := 8;
    constant GRID              : natural := 4;      -- patches per side
    constant SEQ_LEN           : natural := 16;     -- tokens
    constant PATCH_DIM         : natural := 192;    -- values per patch

    -- ── Transformer ─────────────────────────────────────────────
    constant D_MODEL           : natural := 64;
    constant D_FF              : natural := 128;
    constant N_HEADS           : natural := 1;
    constant N_LAYERS          : natural := 1;
    constant N_CLASSES         : natural := 10;

    -- ── Fixed point ─────────────────────────────────────────────
    constant Q_BITS            : natural := 7;      -- Q1.7
    constant Q_SCALE           : natural := 128;    -- integer representing 1.0
    constant ACC_BITS          : natural := 32;     -- PE accumulator width
    constant LN_HEADROOM       : natural := 2;      -- extra >> on LayerNorm out
    constant ATTN_SHIFT        : natural := 10;     -- Q.K^T requant, folds 1/sqrt(d)
    constant GAP_SHIFT         : natural := 4;      -- average pool over SEQ_LEN
    constant INT8_MIN         : integer := -128;
    constant INT8_MAX         : integer := 127;

    -- ── PE array ────────────────────────────────────────────────
    constant PE_ROWS           : natural := 16;     -- maps to tokens (M)
    constant PE_COLS           : natural := 4;      -- maps to an N tile
    constant N_PE              : natural := 64;     -- MACs per cycle

    -- ── Derived sizes (for reference / sizing memories) ─────────
    constant TOTAL_PARAM_BYTES : natural := 46986;
    constant TOTAL_GEMM_CYCLES : natural := 11968;  -- PE-array cycles per image

    -- ── Types ───────────────────────────────────────────────────
    subtype q8_t   is signed(7 downto 0);
    subtype acc_t  is signed(31 downto 0);

    -- One PE-array column slice: PE_ROWS activations read in parallel.
    type q8_row_t  is array (0 to PE_ROWS - 1) of q8_t;
    -- One weight slice: PE_COLS weights for the current k.
    type q8_col_t  is array (0 to PE_COLS - 1) of q8_t;
    -- Accumulator readout: one column's worth of results.
    type acc_col_t is array (0 to PE_COLS - 1) of acc_t;
    -- Saturating requantiser: arithmetic shift right, then clamp to int8.
    -- Shared by every stage that closes out a matrix multiply.
    function requantize (acc : signed; shift : natural) return signed;

    -- Saturating int8 add, used by the residual connections.
    function add_sat8 (a : signed(7 downto 0); b : signed(7 downto 0))
        return signed;

    -- Index of the most significant set bit (leading-one detector), 0 for 0.
    function leading_one (v : unsigned) return natural;

    -- Bits needed to index n distinct values, minimum 1.
    function clog2 (n : positive) return natural;

end package vit_pkg;

package body vit_pkg is

    function requantize (acc : signed; shift : natural) return signed is
        variable shifted : signed(acc'length - 1 downto 0);
    begin
        -- shift_right on a signed value is arithmetic and rounds toward
        -- negative infinity, matching Python's and numpy's >> operators.
        shifted := shift_right(acc, shift);
        if shifted > to_signed(INT8_MAX, acc'length) then
            return to_signed(INT8_MAX, 8);
        elsif shifted < to_signed(INT8_MIN, acc'length) then
            return to_signed(INT8_MIN, 8);
        else
            return resize(shifted, 8);
        end if;
    end function requantize;

    function add_sat8 (a : signed(7 downto 0); b : signed(7 downto 0))
        return signed is
        variable sum : signed(8 downto 0);
    begin
        sum := resize(a, 9) + resize(b, 9);
        if sum > to_signed(INT8_MAX, 9) then
            return to_signed(INT8_MAX, 8);
        elsif sum < to_signed(INT8_MIN, 9) then
            return to_signed(INT8_MIN, 8);
        else
            return resize(sum, 8);
        end if;
    end function add_sat8;

    function leading_one (v : unsigned) return natural is
    begin
        -- Priority encoder: scan from the top, return the first set bit.
        for i in v'length - 1 downto 0 loop
            if v(i) = '1' then
                return i;
            end if;
        end loop;
        return 0;
    end function leading_one;

    function clog2 (n : positive) return natural is
        variable bits : natural := 0;
        variable v    : positive := 1;
    begin
        while v < n loop
            v    := v * 2;
            bits := bits + 1;
        end loop;
        if bits = 0 then
            return 1;                       -- always give at least one bit
        end if;
        return bits;
    end function clog2;

end package body vit_pkg;
