--------------------------------------------------------------------------------
-- weight_rom.vhd -- block-RAM weight store for the PE array
--
-- Holds every trained parameter the array multiplies by: the patch projection,
-- the fused QKV projection, the attention output projection, both FFN layers,
-- and the classifier. Positional embeddings and bias vectors live elsewhere
-- (they are added, not multiplied, and are tiny).
--
-- Layout
-- ------
-- One word supplies the PE_COLS weights the array needs on a given cycle:
--
--     word[base + t*K + k] = { W[t*PE_COLS + 0][k], ... W[t*PE_COLS + 3][k] }
--
-- for output tile t and reduction index k. So walking addresses sequentially
-- from a stage's base address streams exactly the operands a matmul consumes,
-- in order, one word per cycle, with no address arithmetic beyond an
-- increment. The interleaving across output channels is done once, offline, by
-- sw/export_weights.py -- it costs nothing at run time and it is why the
-- weight side of the array never stalls.
--
-- The whole store is about 45 KB, which is 20 BRAM18 blocks of the 100
-- available. The MNIST design this replaces kept its weights in LUT-based
-- distributed ROM and hit 89% LUT occupancy as a result; moving them into real
-- block RAM is the single biggest reason this design fits with room to spare.
--
-- Initialisation
-- --------------
-- Contents come from a hex file, one 2-digit byte per line, PE_COLS bytes per
-- word, generated by sw/export_weights.py. Reading it in an impure function at
-- elaboration works in GHDL for simulation and is inferred as a ROM
-- initialisation by Vivado for synthesis, so simulation and hardware are
-- guaranteed to hold identical coefficients.
--------------------------------------------------------------------------------

library ieee;
    use ieee.std_logic_1164.all;
    use ieee.numeric_std.all;

library std;
    use std.textio.all;

    use work.vit_pkg.all;

entity weight_rom is
    generic (
        DEPTH     : positive := 11456;      -- words, one per array cycle
        INIT_FILE : string   := "weights_rom.hex"
    );
    port (
        clk     : in  std_logic;
        i_addr  : in  unsigned(clog2(DEPTH) - 1 downto 0);
        i_re    : in  std_logic;
        o_wdata : out q8_col_t
    );
end entity weight_rom;

architecture rtl of weight_rom is

    type rom_t is array (0 to DEPTH - 1) of q8_col_t;

    -- Parse the hex file into the ROM image. Any shortfall is left as zero and
    -- reported, so a truncated or missing weight file shows up as a loud
    -- warning at elaboration instead of silently inferring a garbage network.
    impure function load_rom (path : string) return rom_t is
        file     f      : text;
        variable status : file_open_status;
        variable l      : line;
        variable byte_s : string(1 to 2);
        variable rom    : rom_t := (others => (others => (others => '0')));
        variable idx    : natural := 0;      -- byte index across the whole ROM
        variable v      : integer;

        function hex_digit (c : character) return integer is
        begin
            case c is
                when '0' to '9' => return character'pos(c) - character'pos('0');
                when 'a' to 'f' => return character'pos(c) - character'pos('a') + 10;
                when 'A' to 'F' => return character'pos(c) - character'pos('A') + 10;
                when others =>
                    report "weight_rom: bad hex character '" & c & "'"
                        severity failure;
                    return 0;
            end case;
        end function;
    begin
        file_open(status, f, path, read_mode);
        if status /= open_ok then
            report "weight_rom: cannot open '" & path &
                   "'; ROM left zeroed (expected only in unit tests)"
                severity warning;
            return rom;
        end if;

        while not endfile(f) and idx < DEPTH * PE_COLS loop
            readline(f, l);
            if l'length >= 2 then
                read(l, byte_s);
                v := hex_digit(byte_s(1)) * 16 + hex_digit(byte_s(2));
                if v > 127 then                 -- two's complement byte
                    v := v - 256;
                end if;
                rom(idx / PE_COLS)(idx mod PE_COLS) := to_signed(v, 8);
                idx := idx + 1;
            end if;
        end loop;
        file_close(f);

        if idx /= DEPTH * PE_COLS then
            report "weight_rom: '" & path & "' held " & integer'image(idx) &
                   " bytes, expected " & integer'image(DEPTH * PE_COLS)
                severity warning;
        end if;
        return rom;
    end function load_rom;

    -- `constant` rather than a signal: this is read-only, so the synthesiser
    -- maps it into initialised block RAM instead of inferring write logic.
    constant ROM : rom_t := load_rom(INIT_FILE);

begin

    -- Synchronous read with no reset, so it infers block RAM (see act_ram.vhd).
    p_rom : process(clk) is
    begin
        if rising_edge(clk) then
            if i_re = '1' then
                o_wdata <= ROM(to_integer(i_addr));
            end if;
        end if;
    end process p_rom;

end architecture rtl;
