#!/usr/bin/env python3
"""
export_weights.py -- lay the trained int8 weights out the way the array eats them.

The PE array needs, on cycle k of output tile t, the PE_COLS weights belonging
to output channels t*PE_COLS .. t*PE_COLS+3 at reduction index k. Producing that
ordering offline turns weight fetch at run time into a bare address increment,
which is why the weight side of the array never stalls. Nothing here is clever;
it just moves the interleaving from hardware into a build step.

Outputs (into cifar10_vit/rtl/):
    weights_rom.hex   one byte per line, PE_COLS bytes per word, stages
                      concatenated in execution order
    bias_rom.hex      PE_COLS accumulator preloads per tile, 32-bit words,
                      already scaled by Q_SCALE
    pos_embed.hex     positional embeddings, feature-major like act_ram
    stage_map.vhd     the address map, generated so the controller and the
                      ROM layout cannot disagree

The classifier has N_CLASSES = 10 outputs, which is not a multiple of PE_COLS,
so it is padded to 12 with zero weights and a strongly negative bias. Padding
with zero bias would leave two phantom classes tied at zero that could win the
argmax on a weak image; a large negative bias makes them unselectable.
"""
from __future__ import annotations

import argparse
from pathlib import Path

import numpy as np

from golden_model import Weights
from model_config import CONFIG
from quant_ops import Q_SCALE

CFG = CONFIG
PAD_BIAS = -(1 << 20)          # keeps padded classifier outputs out of argmax


class Stage:
    """One matrix multiply's worth of ROM, in array-consumption order."""

    def __init__(self, name: str, w: np.ndarray, bias: np.ndarray | None,
                 k: int, shift: int):
        n_out = w.shape[0]
        pad = (-n_out) % CFG.pe_cols
        if pad:
            w = np.vstack([w, np.zeros((pad, w.shape[1]), dtype=w.dtype)])
            b = np.zeros(n_out + pad, dtype=np.int64)
            if bias is not None:
                b[:n_out] = bias
            b[n_out:] = PAD_BIAS // Q_SCALE
            bias = b
        elif bias is None:
            bias = np.zeros(n_out, dtype=np.int64)

        self.name = name
        self.w = w.astype(np.int64)
        self.bias = np.asarray(bias, dtype=np.int64)
        self.k = k
        self.shift = shift
        self.n_out = w.shape[0]
        self.n_tiles = self.n_out // CFG.pe_cols
        assert self.w.shape == (self.n_out, k), (self.w.shape, k)

    def rom_bytes(self) -> list[int]:
        out: list[int] = []
        for t in range(self.n_tiles):
            for kk in range(self.k):
                for c in range(CFG.pe_cols):
                    out.append(int(self.w[t * CFG.pe_cols + c, kk]) & 0xFF)
        return out

    def bias_words(self) -> list[int]:
        return [int(self.bias[t * CFG.pe_cols + c]) * Q_SCALE
                for t in range(self.n_tiles) for c in range(CFG.pe_cols)]


def build_stages(w: Weights) -> list[Stage]:
    d, f = CFG.d_model, CFG.d_ff
    # Q, K and V are one fused projection so the token matrix is read from
    # memory once instead of three times.
    qkv = np.vstack([w.wq, w.wk, w.wv])
    return [
        Stage("patch_embed", w.patch_proj_w, w.patch_proj_b, CFG.patch_dim, CFG.q_bits),
        Stage("qkv",         qkv,            None,           d,             CFG.q_bits),
        Stage("out_proj",    w.wo,           None,           d,             CFG.q_bits),
        Stage("fc1",         w.w1,           w.b1,           d,             CFG.q_bits),
        Stage("fc2",         w.w2,           w.b2,           f,             CFG.q_bits),
        Stage("classifier",  w.cls_w,        w.cls_b,        d,             CFG.q_bits),
    ]


def write_hex_bytes(path: Path, data: list[int]) -> None:
    path.write_text("".join(f"{b & 0xFF:02X}\n" for b in data))


def write_hex_words(path: Path, data: list[int], width: int = 8) -> None:
    path.write_text("".join(f"{v & ((1 << (4 * width)) - 1):0{width}X}\n"
                            for v in data))


def render_stage_map(stages: list[Stage], rom_words: int,
                     bias_entries: int) -> str:
    lines = [
        "--------------------------------------------------------------------------------",
        "-- stage_map.vhd -- generated by cifar10_vit/sw/export_weights.py; DO NOT EDIT.",
        "--",
        "-- Where each matrix multiply's weights start in the ROM, and how big it is.",
        "-- Generated alongside the ROM image itself so the controller and the data",
        "-- cannot disagree about the layout.",
        "--------------------------------------------------------------------------------",
        "",
        "library ieee;",
        "    use ieee.std_logic_1164.all;",
        "    use ieee.numeric_std.all;",
        "",
        "package stage_map is",
        "",
        f"    constant ROM_WORDS   : natural := {rom_words};",
        f"    constant BIAS_ENTRIES: natural := {bias_entries};",
        "",
    ]
    rom_off, bias_off = 0, 0
    for s in stages:
        u = s.name.upper()
        lines += [
            f"    -- {s.name}: {s.n_out} outputs, K = {s.k}, {s.n_tiles} tiles",
            f"    constant {u}_ROM_BASE  : natural := {rom_off};",
            f"    constant {u}_BIAS_BASE : natural := {bias_off};",
            f"    constant {u}_K         : natural := {s.k};",
            f"    constant {u}_TILES     : natural := {s.n_tiles};",
            f"    constant {u}_SHIFT     : natural := {s.shift};",
            "",
        ]
        rom_off += s.n_tiles * s.k
        bias_off += s.n_tiles * CONFIG.pe_cols
    lines += ["end package stage_map;", ""]
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser()
    root = Path(__file__).resolve().parents[1]
    ap.add_argument("--weights", type=Path, default=root / "weights_int8")
    ap.add_argument("--out", type=Path, default=root / "rtl")
    args = ap.parse_args()

    w = Weights.load(args.weights)
    stages = build_stages(w)

    rom: list[int] = []
    bias: list[int] = []
    print(f"{'stage':<14}{'outputs':>8}{'K':>6}{'tiles':>7}{'rom base':>10}{'words':>8}")
    for s in stages:
        base = len(rom)
        rom += s.rom_bytes()
        bias += s.bias_words()
        print(f"{s.name:<14}{s.n_out:>8}{s.k:>6}{s.n_tiles:>7}"
              f"{base // CFG.pe_cols:>10}{s.n_tiles * s.k:>8}")

    rom_words = len(rom) // CFG.pe_cols
    assert len(rom) % CFG.pe_cols == 0

    args.out.mkdir(parents=True, exist_ok=True)
    write_hex_bytes(args.out / "weights_rom.hex", rom)
    write_hex_words(args.out / "bias_rom.hex", bias)

    # Positional embeddings in act_ram's feature-major order: one line per
    # feature, holding that feature across all SEQ_LEN tokens.
    pos = w.pos_embed                                   # (seq_len, d_model)
    pos_bytes = [int(pos[t, k]) & 0xFF
                 for k in range(CFG.d_model) for t in range(CFG.seq_len)]
    write_hex_bytes(args.out / "pos_embed.hex", pos_bytes)

    (args.out / "stage_map.vhd").write_text(
        render_stage_map(stages, rom_words, len(bias)))

    total_cycles = sum(s.n_tiles * s.k for s in stages)
    print(f"\nweight ROM   {rom_words:,} words ({len(rom):,} bytes)")
    print(f"bias ROM     {len(bias):,} entries")
    print(f"pos_embed    {len(pos_bytes):,} bytes")
    print(f"GEMM cycles  {total_cycles:,} per image "
          f"({total_cycles / 100e6 * 1e6:.1f} us at 100 MHz)")
    print(f"\nwrote weights_rom.hex, bias_rom.hex, pos_embed.hex, "
          f"stage_map.vhd to {args.out}")


if __name__ == "__main__":
    main()
