#!/usr/bin/env python3
"""
gen_layernorm_vectors.py -- golden vectors for sim/tb_layernorm.vhd.

`layernorm_q` in quant_ops.py is the specification for rtl/layernorm.vhd. The
expected values here come from calling it directly, so the testbench and the
RTL share no arithmetic and a common mistake cannot cancel out.

The RTL normalises all SEQ_LEN tokens at once, because act_ram is
feature-major: one memory word holds one feature across every token, so
streaming D_MODEL words feeds every token's statistics accumulator
simultaneously. The vectors are therefore emitted in that same feature-major
word order.

File format:
    # comment lines and blank lines are skipped
    CASE <name>
    IN   <SEQ_LEN values>      x D_MODEL lines   (feature-major words)
    OUT  <SEQ_LEN values>      x D_MODEL lines   (feature-major words)

The cases are chosen to hit the parts of this algorithm that actually break:

  * a constant row has variance exactly zero, which must not divide by zero --
    the reference normalises it to all zeros
  * rows of all INT8_MIN and all INT8_MAX check the accumulator widths and the
    saturation at both ends
  * a single large outlier makes the variance jump several binades
  * mostly-negative rows catch the classic bug of implementing the output
    shift as a truncating divide instead of an arithmetic (floor) shift, which
    is wrong by one on every negative element
  * variances placed just below and just above a power of two catch off-by-one
    errors in the leading-one detector, which is where the shift is decided
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from model_config import CONFIG
from quant_ops import layernorm_q

CFG = CONFIG


def _variance_targeted(rng, target_var: float) -> np.ndarray:
    """A token whose integer variance lands near `target_var`."""
    sd = max(1.0, np.sqrt(target_var))
    row = np.rint(rng.normal(0.0, sd, size=CFG.d_model))
    return np.clip(row, -128, 127).astype(np.int32)


def build_cases() -> list[tuple[str, np.ndarray]]:
    rng = np.random.default_rng(11)
    s, d = CFG.seq_len, CFG.d_model
    cases: list[tuple[str, np.ndarray]] = []

    def add(name: str, tokens: np.ndarray) -> None:
        assert tokens.shape == (s, d), tokens.shape
        cases.append((name, tokens.astype(np.int32)))

    add("constant_zero", np.zeros((s, d)))
    add("constant_42", np.full((s, d), 42))
    add("all_int8_min", np.full((s, d), -128))
    add("all_int8_max", np.full((s, d), 127))

    # Each token constant but different from its neighbours: still zero
    # variance per token, so every output row must be zero.
    add("per_token_constant",
        np.repeat(np.arange(-128, -128 + s).reshape(s, 1), d, axis=1))

    # One huge outlier against an otherwise flat row.
    t = np.zeros((s, d))
    t[:, 0] = 127
    t[:, 1] = -128
    add("outliers", t)

    # Mostly negative: catches truncate-toward-zero instead of floor.
    add("mostly_negative", rng.integers(-128, -40, size=(s, d)))
    add("mostly_positive", rng.integers(40, 128, size=(s, d)))

    # Variances straddling powers of two, where the leading-one detector -- and
    # therefore the chosen shift -- changes.
    for exp in (2, 4, 6, 8, 10, 12):
        for delta in (-1, 0, 1):
            target = float(2 ** exp + delta)
            toks = np.stack([_variance_targeted(rng, target) for _ in range(s)])
            add(f"var_2e{exp}{delta:+d}", toks)

    # Plain random rows across the full range.
    for i in range(6):
        add(f"random_{i}", rng.integers(-128, 128, size=(s, d)))

    return cases


def main() -> None:
    out = Path(__file__).resolve().parents[1] / "sim" / "vectors"
    out.mkdir(parents=True, exist_ok=True)
    path = out / "layernorm_vectors.txt"

    cases = build_cases()
    lines = [
        "# layernorm vectors: generated by sw/gen_layernorm_vectors.py",
        f"# SEQ_LEN={CFG.seq_len} D_MODEL={CFG.d_model} "
        f"LN_HEADROOM={CFG.ln_headroom}",
        "# each case: D_MODEL input words then D_MODEL output words,",
        "# each word holding one feature across all SEQ_LEN tokens",
        "",
    ]

    zero_var_cases = 0
    for name, tokens in cases:
        expected = layernorm_q(tokens, CFG.ln_headroom)
        if np.all(expected == 0):
            zero_var_cases += 1
        lines.append(f"CASE {name}")
        for k in range(CFG.d_model):
            lines.append(" ".join(f"{int(v):5d}" for v in tokens[:, k]))
        for k in range(CFG.d_model):
            lines.append(" ".join(f"{int(v):5d}" for v in expected[:, k]))
        lines.append("")

    path.write_text("\n".join(lines) + "\n")
    print(f"wrote {path}: {len(cases)} cases, "
          f"{len(cases) * CFG.d_model * 2} words")
    print(f"  {zero_var_cases} cases normalise to all zeros (zero variance)")

    # Report the spread actually exercised, so a change that quietly stops
    # covering the interesting shifts is visible here.
    shifts = set()
    for _, tokens in cases:
        for row in tokens:
            r = row.astype(np.int64)
            mean = int(r.sum()) >> int(np.log2(CFG.d_model))
            msq = int((r * r).sum()) >> int(np.log2(CFG.d_model))
            var = max(0, msq - mean * mean)
            lod = 0 if var == 0 else int(var).bit_length() - 1
            shifts.add((lod + 1) // 2)
    print(f"  output shifts exercised: {sorted(shifts)}")


if __name__ == "__main__":
    main()
