#!/usr/bin/env python3
"""
gen_elem_vectors.py -- golden vectors for sim/tb_elem_op.vhd.

Covers all four elementwise modes against the same primitives the golden model
uses, so the RTL is checked against the reference rather than against a second
hand-written copy of the arithmetic:

    POS   add_sat(a, pos)        positional embedding after the stem
    ADD   add_sat(a, b)          the residual connections
    GELU  GELU_LUT[a & 0xFF]     FFN activation
    GAP   sat8(sum(a) >> 4)      global average pool over the token axis

Format, one line per word, '#' comments skipped:

    MODE <code> <n_words>          code: 0=POS 1=ADD 2=GELU 3=GAP,
                                   matching the ELEM_* encodings in vit_pkg
    <SEQ_LEN a values> <SEQ_LEN b values> <SEQ_LEN expected values>

b is unused by GELU and GAP but is still emitted so every line has the same
shape and the testbench parser stays trivial.

The values are chosen to hit the edges that matter: saturation at both ends of
the residual adds, the GELU table's wrap from positive to negative indices at
128, and a GAP case whose token sum overflows int8 before the shift brings it
back (which is where a too-narrow accumulator would show up).
"""
from __future__ import annotations

from pathlib import Path

import numpy as np

from model_config import CONFIG
from quant_ops import GELU_LUT, add_sat, sat8

CFG = CONFIG

# Must match the ELEM_* constants in vit_pkg.vhd. A numeric code rather than a
# name because VHDL's string `read` does not skip leading whitespace, which
# makes name parsing in the testbench needlessly fragile.
MODE_CODES = {"POS": 0, "ADD": 1, "GELU": 2, "GAP": 3}


def build() -> list[tuple[str, np.ndarray, np.ndarray, np.ndarray]]:
    rng = np.random.default_rng(5)
    s = CFG.seq_len
    out = []

    def block(rows: int) -> np.ndarray:
        return rng.integers(-128, 128, size=(rows, s)).astype(np.int32)

    # ── POS: saturating add of a stored embedding ───────────────────────────
    a = np.vstack([block(CFG.d_model - 4),
                   np.full((2, s), 127), np.full((2, s), -128)])
    b = np.vstack([block(CFG.d_model - 4),
                   np.full((2, s), 100), np.full((2, s), -100)])
    out.append(("POS", a, b, add_sat(a, b)))

    # ── ADD: residual, same saturation behaviour ────────────────────────────
    a = np.vstack([np.full((2, s), 127), np.full((2, s), -128), block(60)])
    b = np.vstack([np.full((2, s), 127), np.full((2, s), -128), block(60)])
    out.append(("ADD", a, b, add_sat(a, b)))

    # ── GELU: sweep every table entry, then random ──────────────────────────
    # 256 entries over SEQ_LEN lanes needs 16 words to cover the whole table.
    sweep = np.arange(256).reshape(16, s)
    sweep = np.where(sweep < 128, sweep, sweep - 256).astype(np.int32)
    a = np.vstack([sweep, block(CFG.d_ff - 16)])
    b = np.zeros_like(a)
    expected = GELU_LUT[a & 0xFF].astype(np.int32)
    out.append(("GELU", a, b, expected))

    # ── GAP: reduction across the token axis ────────────────────────────────
    a = np.vstack([
        np.full((1, s), 127),        # sum 2032, well past int8 before the shift
        np.full((1, s), -128),       # sum -2048
        np.zeros((1, s)),
        block(CFG.d_model - 3),
    ]).astype(np.int32)
    b = np.zeros_like(a)
    pooled = sat8(a.astype(np.int64).sum(axis=1) >> CFG.gap_shift)
    expected = np.zeros_like(a)
    expected[:, 0] = pooled          # result in lane 0, other lanes zeroed
    out.append(("GAP", a, b, expected))

    return out


def main() -> None:
    out_dir = Path(__file__).resolve().parents[1] / "sim" / "vectors"
    out_dir.mkdir(parents=True, exist_ok=True)
    path = out_dir / "elem_vectors.txt"

    lines = ["# elementwise vectors: generated by sw/gen_elem_vectors.py",
             f"# SEQ_LEN={CFG.seq_len} GAP_SHIFT={CFG.gap_shift}", ""]
    total = 0
    for name, a, b, e in build():
        assert a.shape == b.shape == e.shape
        lines.append(f"MODE {MODE_CODES[name]} {a.shape[0]}")
        for k in range(a.shape[0]):
            lines.append(
                " ".join(f"{int(v):5d}" for v in a[k]) + "   " +
                " ".join(f"{int(v):5d}" for v in b[k]) + "   " +
                " ".join(f"{int(v):5d}" for v in e[k]))
            total += 1
        lines.append("")
        sat = int((np.abs(e) == 127).sum() + (e == -128).sum())
        print(f"{name:<6} {a.shape[0]:>4} words, {sat:>4} saturated values")

    path.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {path}: {total} words")


if __name__ == "__main__":
    main()
